import type { RiskCriterionId } from "@/types";

export interface RiskCriterionDefinition {
  id: RiskCriterionId;
  label: string;
  maxScore: number;
  patterns: RegExp[];
}

/**
 * 10 critères juridiques obligatoires (analyse type juriste).
 * Total maxScore = 100.
 */
export const RISK_CRITERIA: RiskCriterionDefinition[] = [
  {
    id: "renouvellement_tacite",
    label: "Renouvellement tacite",
    maxScore: 12,
    patterns: [
      /renouvellement\s+tacite/i,
      /renouvellement\s+automatique/i,
      /tacite\s+reconduction/i,
      /reconduction\s+tacite/i,
      /reconduit\s+automatiquement/i,
      /renouvel[ée]?\s+par\s+tacite/i,
      /prorogation\s+automatique/i,
      /reconduction\s+automatique/i,
      /sauf\s+(?:d[ée]nonciation|r[ée]siliation)\s+pr[ée]alable/i,
    ],
  },
  {
    id: "frais_caches",
    label: "Frais cachés",
    maxScore: 10,
    patterns: [
      /frais\s+cach[ée]s/i,
      /frais\s+annexes/i,
      /frais\s+suppl[ée]mentaires/i,
      /frais\s+non\s+(?:inclus|indiqu[ée]s)/i,
      /co[uû]ts?\s+additionnels/i,
      /hors\s+forfait/i,
      /sauf\s+frais/i,
      /commission\s+de\s+dossier/i,
      /frais\s+de\s+dossier/i,
      /frais\s+de\s+tenue/i,
      /surco[uû]ts?/i,
      /frais\s+de\s+gestion/i,
      /hors\s+taxes?\s+et\s+frais/i,
    ],
  },
  {
    id: "penalites",
    label: "Pénalités",
    maxScore: 10,
    patterns: [
      /p[ée]nalit[ée]s?/i,
      /clause\s+p[ée]nale/i,
      /astreinte/i,
      /int[ée]r[êe]ts?\s+de\s+retard/i,
      /majorations?/i,
      /dommages[\s-]et[\s-]int[ée]r[êe]ts/i,
      /indemnit[ée]s?\s+forfaitaires?/i,
      /amende\s+contractuelle/i,
      /p[ée]nalit[ée]\s+de\s+retard/i,
    ],
  },
  {
    id: "clauses_abusives",
    label: "Clauses abusives",
    maxScore: 12,
    patterns: [
      /clause\s+abusive/i,
      /clauses?\s+abusives?/i,
      /d[ée]s[ée]quilibre\s+(?:significatif|manifeste)/i,
      /renonciation\s+(?:totale\s+)?(?:à|a)\s+(?:tout\s+)?droit/i,
      /limitation\s+(?:totale\s+)?de\s+responsabilit[ée]/i,
      /exon[ée]ration\s+(?:totale\s+)?de\s+responsabilit[ée]/i,
      /sans\s+recours\s+possible/i,
      /irrevocable/i,
      /irr[ée]vocable/i,
      /non\s+negociable/i,
      /non\s+n[ée]gociable/i,
      /au\s+seul\s+profit/i,
      /pouvoir\s+discr[ée]tionnaire/i,
      /modification\s+unilat[ée]rale/i,
    ],
  },
  {
    id: "obligations_importantes",
    label: "Obligations importantes",
    maxScore: 10,
    patterns: [
      /obligation\s+(?:de|essentielle|principale|contractuelle)/i,
      /doit\s+imp[ée]rativement/i,
      /tenu\s+(?:de|à|a)\b/i,
      /il\s+est\s+fait\s+obligation/i,
      /garantie\s+autonome/i,
      /caution\s+solidaire/i,
      /responsabilit[ée]\s+illimit[ée]e/i,
      /exclusivit[ée]/i,
      /non[\s-]concurrence/i,
      /obligation\s+de\s+r[ée]sultat/i,
      /obligation\s+de\s+moyens/i,
    ],
  },
  {
    id: "delais",
    label: "Délais",
    maxScore: 8,
    patterns: [
      /d[ée]lai(?:s)?\b/i,
      /pr[ée]avis/i,
      /[ée]ch[ée]ance/i,
      /sous\s+\d+\s*(?:h|heures?|jours?|mois)/i,
      /dans\s+un\s+d[ée]lai/i,
      /dans\s+les?\s+\d+\s*(?:h|heures?|jours?|mois)/i,
      /d[ée]lai\s+(?:de\s+)?(?:48\s*h|24\s*h|72\s*h)/i,
      /sous\s+huit\s+jours/i,
      /sous\s+8\s+jours/i,
      /sous\s+quinze\s+jours/i,
      /au\s+plus\s+tard/i,
      /date\s+limite/i,
      /sans\s+d[ée]lai/i,
      /r[ée]ponse\s+imm[ée]diate/i,
    ],
  },
  {
    id: "resiliation",
    label: "Résiliation",
    maxScore: 10,
    patterns: [
      /r[ée]siliation/i,
      /r[ée]silier/i,
      /d[ée]nonciation/i,
      /mettre\s+fin\s+au\s+contrat/i,
      /rupture\s+(?:du\s+contrat|anticip[ée]e)/i,
      /r[ée]siliation\s+de\s+plein\s+droit/i,
      /r[ée]siliation\s+imm[ée]diate/i,
      /conditions?\s+de\s+r[ée]siliation/i,
      /modalit[ée]s?\s+de\s+r[ée]siliation/i,
      /pr[ée]avis\s+de\s+r[ée]siliation/i,
    ],
  },
  {
    id: "augmentation_tarif",
    label: "Augmentation de tarif",
    maxScore: 8,
    patterns: [
      /augmentation\s+(?:de\s+)?(?:tarif|prix|loyer|cotisation)/i,
      /hausse\s+(?:de\s+)?(?:tarif|prix|loyer|cotisation)/i,
      /r[ée]vision\s+(?:de\s+)?(?:tarif|prix|loyer|index)/i,
      /indexation/i,
      /revalorisation/i,
      /modification\s+(?:des?\s+)?(?:prix|tarifs)/i,
      /peut\s+(?:[êe]tre\s+)?(?:augment[ée]|r[ée]vis[ée])/i,
      /tarif\s+(?:r[ée]visable|variable)/i,
      /prix\s+r[ée]visable/i,
      /selon\s+l['']indice/i,
    ],
  },
  {
    id: "engagement",
    label: "Engagement",
    maxScore: 10,
    patterns: [
      /\bengagement\b/i,
      /s'?engage(?:nt)?\s+[àa]/i,
      /dur[ée]e\s+(?:minimale\s+)?d['']engagement/i,
      /p[ée]riode\s+d['']engagement/i,
      /engagement\s+(?:minimum|minimal|ferme|irr[ée]vocable)/i,
      /li[ée]\s+pendant/i,
      /pour\s+une\s+dur[ée]e\s+(?:de\s+)?\d+/i,
      /contrat\s+[àa]\s+dur[ée]e\s+(?:d[ée]termin[ée]e|ind[ée]termin[ée]e)/i,
      /engagement\s+financier/i,
      /souscription\s+ferme/i,
    ],
  },
  {
    id: "sanctions",
    label: "Sanctions",
    maxScore: 10,
    patterns: [
      /sanctions?/i,
      /mise\s+en\s+demeure/i,
      /poursuites?\s+judiciaires?/i,
      /\bamende\b/i,
      /r[ée]vocation/i,
      /suspension/i,
      /d[ée]ch[ée]ance/i,
      /exclusion/i,
      /interdiction/i,
      /astreinte\s+judiciaire/i,
      /recouvrement\s+forc[ée]/i,
      /contentieux/i,
    ],
  },
];
